// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard
{
    /// <summary>
    /// Builds and executes requests for operations under \api\mobile\studentidcard
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StudentidcardRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Schuly.Plugin.Schulware.Client.api.mobile.studentidcard.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.Item.WithReport_ItemRequestBuilder"/></returns>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.Item.WithReport_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("report_id", position);
                return new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.Item.WithReport_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Schuly.Plugin.Schulware.Client.api.mobile.studentidcard.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.Item.WithReport_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.Item.WithReport_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("report_id", position);
                return new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.Item.WithReport_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.StudentidcardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StudentidcardRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/mobile/studentidcard", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.StudentidcardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StudentidcardRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/mobile/studentidcard", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
