// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AbsenceNoticeStatusDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The additionalInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_additionalInfo? AdditionalInfo { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_additionalInfo AdditionalInfo { get; set; }
#endif
        /// <summary>The code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_code? Code { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_code Code { get; set; }
#endif
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_comment? Comment { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_comment Comment { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_id? Id { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_id Id { get; set; }
#endif
        /// <summary>The iso2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso2? Iso2 { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso2 Iso2 { get; set; }
#endif
        /// <summary>The iso3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso3? Iso3 { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso3 Iso3 { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_name? Name { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_name Name { get; set; }
#endif
        /// <summary>The sort property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_sort? Sort { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_sort Sort { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto"/> and sets the default values.
        /// </summary>
        public AbsenceNoticeStatusDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalInfo", n => { AdditionalInfo = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_additionalInfo>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_additionalInfo.CreateFromDiscriminatorValue); } },
                { "code", n => { Code = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_code>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_code.CreateFromDiscriminatorValue); } },
                { "comment", n => { Comment = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_comment>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_comment.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_id>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_id.CreateFromDiscriminatorValue); } },
                { "iso2", n => { Iso2 = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso2>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso2.CreateFromDiscriminatorValue); } },
                { "iso3", n => { Iso3 = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso3>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso3.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_name>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_name.CreateFromDiscriminatorValue); } },
                { "sort", n => { Sort = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_sort>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_sort.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_additionalInfo>("additionalInfo", AdditionalInfo);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_code>("code", Code);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_comment>("comment", Comment);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_id>("id", Id);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso2>("iso2", Iso2);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso3>("iso3", Iso3);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_name>("name", Name);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_sort>("sort", Sort);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_additionalInfoMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AbsenceNoticeStatusDto_additionalInfo : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_additionalInfoMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_additionalInfoMember1? AbsenceNoticeStatusDtoAdditionalInfoMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_additionalInfoMember1 AbsenceNoticeStatusDtoAdditionalInfoMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_additionalInfo"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_additionalInfo CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_additionalInfo();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AbsenceNoticeStatusDtoAdditionalInfoMember1 = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_additionalInfoMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AbsenceNoticeStatusDtoAdditionalInfoMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AbsenceNoticeStatusDtoAdditionalInfoMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_additionalInfoMember1>(null, AbsenceNoticeStatusDtoAdditionalInfoMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_codeMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AbsenceNoticeStatusDto_code : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_codeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_codeMember1? AbsenceNoticeStatusDtoCodeMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_codeMember1 AbsenceNoticeStatusDtoCodeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_code"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_code CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_code();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AbsenceNoticeStatusDtoCodeMember1 = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_codeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AbsenceNoticeStatusDtoCodeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AbsenceNoticeStatusDtoCodeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_codeMember1>(null, AbsenceNoticeStatusDtoCodeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_commentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AbsenceNoticeStatusDto_comment : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_commentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_commentMember1? AbsenceNoticeStatusDtoCommentMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_commentMember1 AbsenceNoticeStatusDtoCommentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_comment"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_comment CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_comment();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AbsenceNoticeStatusDtoCommentMember1 = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_commentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AbsenceNoticeStatusDtoCommentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AbsenceNoticeStatusDtoCommentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_commentMember1>(null, AbsenceNoticeStatusDtoCommentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AbsenceNoticeStatusDto_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_idMember1? AbsenceNoticeStatusDtoIdMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_idMember1 AbsenceNoticeStatusDtoIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AbsenceNoticeStatusDtoIdMember1 = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AbsenceNoticeStatusDtoIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AbsenceNoticeStatusDtoIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_idMember1>(null, AbsenceNoticeStatusDtoIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso2Member1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AbsenceNoticeStatusDto_iso2 : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso2Member1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso2Member1? AbsenceNoticeStatusDtoIso2Member1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso2Member1 AbsenceNoticeStatusDtoIso2Member1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso2"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso2 CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso2();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AbsenceNoticeStatusDtoIso2Member1 = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso2Member1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AbsenceNoticeStatusDtoIso2Member1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AbsenceNoticeStatusDtoIso2Member1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso2Member1>(null, AbsenceNoticeStatusDtoIso2Member1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso3Member1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AbsenceNoticeStatusDto_iso3 : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso3Member1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso3Member1? AbsenceNoticeStatusDtoIso3Member1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso3Member1 AbsenceNoticeStatusDtoIso3Member1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso3"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso3 CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_iso3();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AbsenceNoticeStatusDtoIso3Member1 = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso3Member1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AbsenceNoticeStatusDtoIso3Member1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AbsenceNoticeStatusDtoIso3Member1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_iso3Member1>(null, AbsenceNoticeStatusDtoIso3Member1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_nameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AbsenceNoticeStatusDto_name : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_nameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_nameMember1? AbsenceNoticeStatusDtoNameMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_nameMember1 AbsenceNoticeStatusDtoNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_name"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_name CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_name();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AbsenceNoticeStatusDtoNameMember1 = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_nameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AbsenceNoticeStatusDtoNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AbsenceNoticeStatusDtoNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_nameMember1>(null, AbsenceNoticeStatusDtoNameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_sortMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AbsenceNoticeStatusDto_sort : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_sortMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_sortMember1? AbsenceNoticeStatusDtoSortMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_sortMember1 AbsenceNoticeStatusDtoSortMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_sort"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_sort CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto.AbsenceNoticeStatusDto_sort();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AbsenceNoticeStatusDtoSortMember1 = new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_sortMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AbsenceNoticeStatusDtoSortMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AbsenceNoticeStatusDtoSortMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto_sortMember1>(null, AbsenceNoticeStatusDtoSortMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
