// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AbsenceDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The additionalPeriod property</summary>
        public int? AdditionalPeriod { get; set; }
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The commentEAB property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommentEAB { get; set; }
#nullable restore
#else
        public string CommentEAB { get; set; }
#endif
        /// <summary>The dateEAB property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateEAB { get; set; }
#nullable restore
#else
        public string DateEAB { get; set; }
#endif
        /// <summary>The dateEAE property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateEAE { get; set; }
#nullable restore
#else
        public string DateEAE { get; set; }
#endif
        /// <summary>The dateFrom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateFrom { get; set; }
#nullable restore
#else
        public string DateFrom { get; set; }
#endif
        /// <summary>The dateTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateTo { get; set; }
#nullable restore
#else
        public string DateTo { get; set; }
#endif
        /// <summary>The excusedDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExcusedDate { get; set; }
#nullable restore
#else
        public string ExcusedDate { get; set; }
#endif
        /// <summary>The hourFrom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HourFrom { get; set; }
#nullable restore
#else
        public string HourFrom { get; set; }
#endif
        /// <summary>The hourTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HourTo { get; set; }
#nullable restore
#else
        public string HourTo { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The isAcknowledged property</summary>
        public bool? IsAcknowledged { get; set; }
        /// <summary>The isExcused property</summary>
        public bool? IsExcused { get; set; }
        /// <summary>The lessons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lessons { get; set; }
#nullable restore
#else
        public string Lessons { get; set; }
#endif
        /// <summary>The profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Profile { get; set; }
#nullable restore
#else
        public string Profile { get; set; }
#endif
        /// <summary>The profileId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileId { get; set; }
#nullable restore
#else
        public string ProfileId { get; set; }
#endif
        /// <summary>The reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The remark property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Remark { get; set; }
#nullable restore
#else
        public string Remark { get; set; }
#endif
        /// <summary>The statusEAB property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusEAB { get; set; }
#nullable restore
#else
        public string StatusEAB { get; set; }
#endif
        /// <summary>The statusEAE property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusEAE { get; set; }
#nullable restore
#else
        public string StatusEAE { get; set; }
#endif
        /// <summary>The studentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StudentId { get; set; }
#nullable restore
#else
        public string StudentId { get; set; }
#endif
        /// <summary>The studentTimestamp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StudentTimestamp { get; set; }
#nullable restore
#else
        public string StudentTimestamp { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The subjectId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectId { get; set; }
#nullable restore
#else
        public string SubjectId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceDto"/> and sets the default values.
        /// </summary>
        public AbsenceDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.AbsenceDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalPeriod", n => { AdditionalPeriod = n.GetIntValue(); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "commentEAB", n => { CommentEAB = n.GetStringValue(); } },
                { "dateEAB", n => { DateEAB = n.GetStringValue(); } },
                { "dateEAE", n => { DateEAE = n.GetStringValue(); } },
                { "dateFrom", n => { DateFrom = n.GetStringValue(); } },
                { "dateTo", n => { DateTo = n.GetStringValue(); } },
                { "excusedDate", n => { ExcusedDate = n.GetStringValue(); } },
                { "hourFrom", n => { HourFrom = n.GetStringValue(); } },
                { "hourTo", n => { HourTo = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isAcknowledged", n => { IsAcknowledged = n.GetBoolValue(); } },
                { "isExcused", n => { IsExcused = n.GetBoolValue(); } },
                { "lessons", n => { Lessons = n.GetStringValue(); } },
                { "profile", n => { Profile = n.GetStringValue(); } },
                { "profileId", n => { ProfileId = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "remark", n => { Remark = n.GetStringValue(); } },
                { "statusEAB", n => { StatusEAB = n.GetStringValue(); } },
                { "statusEAE", n => { StatusEAE = n.GetStringValue(); } },
                { "studentId", n => { StudentId = n.GetStringValue(); } },
                { "studentTimestamp", n => { StudentTimestamp = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "subjectId", n => { SubjectId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("additionalPeriod", AdditionalPeriod);
            writer.WriteStringValue("category", Category);
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("commentEAB", CommentEAB);
            writer.WriteStringValue("dateEAB", DateEAB);
            writer.WriteStringValue("dateEAE", DateEAE);
            writer.WriteStringValue("dateFrom", DateFrom);
            writer.WriteStringValue("dateTo", DateTo);
            writer.WriteStringValue("excusedDate", ExcusedDate);
            writer.WriteStringValue("hourFrom", HourFrom);
            writer.WriteStringValue("hourTo", HourTo);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isAcknowledged", IsAcknowledged);
            writer.WriteBoolValue("isExcused", IsExcused);
            writer.WriteStringValue("lessons", Lessons);
            writer.WriteStringValue("profile", Profile);
            writer.WriteStringValue("profileId", ProfileId);
            writer.WriteStringValue("reason", Reason);
            writer.WriteStringValue("remark", Remark);
            writer.WriteStringValue("statusEAB", StatusEAB);
            writer.WriteStringValue("statusEAE", StatusEAE);
            writer.WriteStringValue("studentId", StudentId);
            writer.WriteStringValue("studentTimestamp", StudentTimestamp);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("subjectId", SubjectId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
