// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GradeDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_comment? Comment { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_comment Comment { get; set; }
#endif
        /// <summary>The course property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_course? Course { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_course Course { get; set; }
#endif
        /// <summary>The courseGrade property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseGrade? CourseGrade { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseGrade CourseGrade { get; set; }
#endif
        /// <summary>The courseId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseId? CourseId { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseId CourseId { get; set; }
#endif
        /// <summary>The courseType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseType? CourseType { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseType CourseType { get; set; }
#endif
        /// <summary>The date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_date? Date { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_date Date { get; set; }
#endif
        /// <summary>The examId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_examId? ExamId { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_examId ExamId { get; set; }
#endif
        /// <summary>The examinationGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto? ExaminationGroups { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto ExaminationGroups { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_id? Id { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_id Id { get; set; }
#endif
        /// <summary>The inputType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_inputType? InputType { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_inputType InputType { get; set; }
#endif
        /// <summary>The isConfirmed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmed? IsConfirmed { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmed IsConfirmed { get; set; }
#endif
        /// <summary>The isConfirmedByTrainer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmedByTrainer? IsConfirmedByTrainer { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmedByTrainer IsConfirmedByTrainer { get; set; }
#endif
        /// <summary>The mark property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_mark? Mark { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_mark Mark { get; set; }
#endif
        /// <summary>The points property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_points? Points { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_points Points { get; set; }
#endif
        /// <summary>The studentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentId? StudentId { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentId StudentId { get; set; }
#endif
        /// <summary>The studentName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentName? StudentName { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentName StudentName { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subject? Subject { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subject Subject { get; set; }
#endif
        /// <summary>The subjectToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subjectToken? SubjectToken { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subjectToken SubjectToken { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_title? Title { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_title Title { get; set; }
#endif
        /// <summary>The weight property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_weight? Weight { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_weight Weight { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto"/> and sets the default values.
        /// </summary>
        public GradeDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.GradeDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comment", n => { Comment = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_comment>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_comment.CreateFromDiscriminatorValue); } },
                { "course", n => { Course = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_course>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_course.CreateFromDiscriminatorValue); } },
                { "courseGrade", n => { CourseGrade = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseGrade>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseGrade.CreateFromDiscriminatorValue); } },
                { "courseId", n => { CourseId = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseId>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseId.CreateFromDiscriminatorValue); } },
                { "courseType", n => { CourseType = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseType>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseType.CreateFromDiscriminatorValue); } },
                { "date", n => { Date = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_date>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_date.CreateFromDiscriminatorValue); } },
                { "examId", n => { ExamId = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_examId>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_examId.CreateFromDiscriminatorValue); } },
                { "examinationGroups", n => { ExaminationGroups = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto>(global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_id>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_id.CreateFromDiscriminatorValue); } },
                { "inputType", n => { InputType = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_inputType>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_inputType.CreateFromDiscriminatorValue); } },
                { "isConfirmed", n => { IsConfirmed = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmed>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmed.CreateFromDiscriminatorValue); } },
                { "isConfirmedByTrainer", n => { IsConfirmedByTrainer = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmedByTrainer>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmedByTrainer.CreateFromDiscriminatorValue); } },
                { "mark", n => { Mark = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_mark>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_mark.CreateFromDiscriminatorValue); } },
                { "points", n => { Points = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_points>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_points.CreateFromDiscriminatorValue); } },
                { "studentId", n => { StudentId = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentId>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentId.CreateFromDiscriminatorValue); } },
                { "studentName", n => { StudentName = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentName>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentName.CreateFromDiscriminatorValue); } },
                { "subject", n => { Subject = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subject>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subject.CreateFromDiscriminatorValue); } },
                { "subjectToken", n => { SubjectToken = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subjectToken>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subjectToken.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_title>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_title.CreateFromDiscriminatorValue); } },
                { "weight", n => { Weight = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_weight>(global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_weight.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_comment>("comment", Comment);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_course>("course", Course);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseGrade>("courseGrade", CourseGrade);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseId>("courseId", CourseId);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseType>("courseType", CourseType);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_date>("date", Date);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_examId>("examId", ExamId);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto>("examinationGroups", ExaminationGroups);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_id>("id", Id);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_inputType>("inputType", InputType);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmed>("isConfirmed", IsConfirmed);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmedByTrainer>("isConfirmedByTrainer", IsConfirmedByTrainer);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_mark>("mark", Mark);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_points>("points", Points);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentId>("studentId", StudentId);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentName>("studentName", StudentName);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subject>("subject", Subject);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subjectToken>("subjectToken", SubjectToken);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_title>("title", Title);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_weight>("weight", Weight);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_commentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_comment : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_commentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_commentMember1? GradeDtoCommentMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_commentMember1 GradeDtoCommentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_comment"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_comment CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_comment();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoCommentMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_commentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoCommentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoCommentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_commentMember1>(null, GradeDtoCommentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_course : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseMember1? GradeDtoCourseMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseMember1 GradeDtoCourseMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_course"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_course CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_course();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoCourseMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoCourseMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoCourseMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseMember1>(null, GradeDtoCourseMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseGradeMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_courseGrade : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseGradeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseGradeMember1? GradeDtoCourseGradeMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseGradeMember1 GradeDtoCourseGradeMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseGrade"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseGrade CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseGrade();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.GradeDtoCourseGradeMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseGradeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoCourseGradeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoCourseGradeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseGradeMember1>(null, GradeDtoCourseGradeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_courseId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseIdMember1? GradeDtoCourseIdMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseIdMember1 GradeDtoCourseIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoCourseIdMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoCourseIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoCourseIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseIdMember1>(null, GradeDtoCourseIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseTypeMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_courseType : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseTypeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseTypeMember1? GradeDtoCourseTypeMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseTypeMember1 GradeDtoCourseTypeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseType"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseType CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_courseType();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoCourseTypeMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseTypeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoCourseTypeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoCourseTypeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_courseTypeMember1>(null, GradeDtoCourseTypeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_dateMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_date : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_dateMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_dateMember1? GradeDtoDateMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_dateMember1 GradeDtoDateMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_date"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_date CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_date();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoDateMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_dateMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoDateMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoDateMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_dateMember1>(null, GradeDtoDateMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_examIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_examId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_examIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_examIdMember1? GradeDtoExamIdMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_examIdMember1 GradeDtoExamIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_examId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_examId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_examId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoExamIdMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_examIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoExamIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoExamIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_examIdMember1>(null, GradeDtoExamIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_idMember1? GradeDtoIdMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_idMember1 GradeDtoIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoIdMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_idMember1>(null, GradeDtoIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_inputTypeMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_inputType : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_inputTypeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_inputTypeMember1? GradeDtoInputTypeMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_inputTypeMember1 GradeDtoInputTypeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_inputType"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_inputType CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_inputType();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoInputTypeMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_inputTypeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoInputTypeMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoInputTypeMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_inputTypeMember1>(null, GradeDtoInputTypeMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_isConfirmed : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedMember1? GradeDtoIsConfirmedMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedMember1 GradeDtoIsConfirmedMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmed"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmed CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmed();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.GradeDtoIsConfirmedMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoIsConfirmedMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoIsConfirmedMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedMember1>(null, GradeDtoIsConfirmedMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedByTrainerMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_isConfirmedByTrainer : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedByTrainerMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedByTrainerMember1? GradeDtoIsConfirmedByTrainerMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedByTrainerMember1 GradeDtoIsConfirmedByTrainerMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmedByTrainer"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmedByTrainer CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_isConfirmedByTrainer();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.GradeDtoIsConfirmedByTrainerMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedByTrainerMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoIsConfirmedByTrainerMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoIsConfirmedByTrainerMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_isConfirmedByTrainerMember1>(null, GradeDtoIsConfirmedByTrainerMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_markMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_mark : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_markMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_markMember1? GradeDtoMarkMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_markMember1 GradeDtoMarkMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_mark"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_mark CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_mark();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.GradeDtoMarkMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_markMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoMarkMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoMarkMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_markMember1>(null, GradeDtoMarkMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_pointsMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_points : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_pointsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_pointsMember1? GradeDtoPointsMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_pointsMember1 GradeDtoPointsMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_points"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_points CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_points();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.GradeDtoPointsMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_pointsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoPointsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoPointsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_pointsMember1>(null, GradeDtoPointsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_studentId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentIdMember1? GradeDtoStudentIdMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentIdMember1 GradeDtoStudentIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoStudentIdMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoStudentIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoStudentIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentIdMember1>(null, GradeDtoStudentIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentNameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_studentName : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentNameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentNameMember1? GradeDtoStudentNameMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentNameMember1 GradeDtoStudentNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentName"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentName CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_studentName();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoStudentNameMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentNameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoStudentNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoStudentNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_studentNameMember1>(null, GradeDtoStudentNameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_subject : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectMember1? GradeDtoSubjectMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectMember1 GradeDtoSubjectMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subject"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subject CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subject();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoSubjectMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoSubjectMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoSubjectMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectMember1>(null, GradeDtoSubjectMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectTokenMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_subjectToken : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectTokenMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectTokenMember1? GradeDtoSubjectTokenMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectTokenMember1 GradeDtoSubjectTokenMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subjectToken"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subjectToken CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_subjectToken();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoSubjectTokenMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectTokenMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoSubjectTokenMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoSubjectTokenMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_subjectTokenMember1>(null, GradeDtoSubjectTokenMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_titleMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_title : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_titleMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_titleMember1? GradeDtoTitleMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_titleMember1 GradeDtoTitleMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_title"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_title CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_title();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.GradeDtoTitleMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_titleMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoTitleMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoTitleMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_titleMember1>(null, GradeDtoTitleMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_weightMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GradeDto_weight : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto_weightMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_weightMember1? GradeDtoWeightMember1 { get; set; }
#nullable restore
#else
            public global::Schuly.Plugin.Schulware.Client.Models.GradeDto_weightMember1 GradeDtoWeightMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_weight"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_weight CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto.GradeDto_weight();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.GradeDtoWeightMember1 = new global::Schuly.Plugin.Schulware.Client.Models.GradeDto_weightMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GradeDtoWeightMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(GradeDtoWeightMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.GradeDto_weightMember1>(null, GradeDtoWeightMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
