// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GradeDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The course property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Course { get; set; }
#nullable restore
#else
        public string Course { get; set; }
#endif
        /// <summary>The courseGrade property</summary>
        public double? CourseGrade { get; set; }
        /// <summary>The courseId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CourseId { get; set; }
#nullable restore
#else
        public string CourseId { get; set; }
#endif
        /// <summary>The courseType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CourseType { get; set; }
#nullable restore
#else
        public string CourseType { get; set; }
#endif
        /// <summary>The date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Date { get; set; }
#nullable restore
#else
        public string Date { get; set; }
#endif
        /// <summary>The examId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExamId { get; set; }
#nullable restore
#else
        public string ExamId { get; set; }
#endif
        /// <summary>The examinationGroups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto? ExaminationGroups { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto ExaminationGroups { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The inputType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputType { get; set; }
#nullable restore
#else
        public string InputType { get; set; }
#endif
        /// <summary>The isConfirmed property</summary>
        public bool? IsConfirmed { get; set; }
        /// <summary>The isConfirmedByTrainer property</summary>
        public bool? IsConfirmedByTrainer { get; set; }
        /// <summary>The mark property</summary>
        public double? Mark { get; set; }
        /// <summary>The points property</summary>
        public double? Points { get; set; }
        /// <summary>The studentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StudentId { get; set; }
#nullable restore
#else
        public string StudentId { get; set; }
#endif
        /// <summary>The studentName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StudentName { get; set; }
#nullable restore
#else
        public string StudentName { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The subjectToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectToken { get; set; }
#nullable restore
#else
        public string SubjectToken { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The weight property</summary>
        public double? Weight { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto"/> and sets the default values.
        /// </summary>
        public GradeDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.GradeDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.GradeDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.GradeDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "course", n => { Course = n.GetStringValue(); } },
                { "courseGrade", n => { CourseGrade = n.GetDoubleValue(); } },
                { "courseId", n => { CourseId = n.GetStringValue(); } },
                { "courseType", n => { CourseType = n.GetStringValue(); } },
                { "date", n => { Date = n.GetStringValue(); } },
                { "examId", n => { ExamId = n.GetStringValue(); } },
                { "examinationGroups", n => { ExaminationGroups = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto>(global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "inputType", n => { InputType = n.GetStringValue(); } },
                { "isConfirmed", n => { IsConfirmed = n.GetBoolValue(); } },
                { "isConfirmedByTrainer", n => { IsConfirmedByTrainer = n.GetBoolValue(); } },
                { "mark", n => { Mark = n.GetDoubleValue(); } },
                { "points", n => { Points = n.GetDoubleValue(); } },
                { "studentId", n => { StudentId = n.GetStringValue(); } },
                { "studentName", n => { StudentName = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "subjectToken", n => { SubjectToken = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "weight", n => { Weight = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("course", Course);
            writer.WriteDoubleValue("courseGrade", CourseGrade);
            writer.WriteStringValue("courseId", CourseId);
            writer.WriteStringValue("courseType", CourseType);
            writer.WriteStringValue("date", Date);
            writer.WriteStringValue("examId", ExamId);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.ExaminationGroupsDto>("examinationGroups", ExaminationGroups);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("inputType", InputType);
            writer.WriteBoolValue("isConfirmed", IsConfirmed);
            writer.WriteBoolValue("isConfirmedByTrainer", IsConfirmedByTrainer);
            writer.WriteDoubleValue("mark", Mark);
            writer.WriteDoubleValue("points", Points);
            writer.WriteStringValue("studentId", StudentId);
            writer.WriteStringValue("studentName", StudentName);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("subjectToken", SubjectToken);
            writer.WriteStringValue("title", Title);
            writer.WriteDoubleValue("weight", Weight);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
