// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserInfoDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The additionalClasses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto>? AdditionalClasses { get; set; }
#nullable restore
#else
        public List<global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto> AdditionalClasses { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addressLine2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine2 { get; set; }
#nullable restore
#else
        public string AddressLine2 { get; set; }
#endif
        /// <summary>The birthday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Birthday { get; set; }
#nullable restore
#else
        public string Birthday { get; set; }
#endif
        /// <summary>The city property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The emailPrivate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailPrivate { get; set; }
#nullable restore
#else
        public string EmailPrivate { get; set; }
#endif
        /// <summary>The entryDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntryDate { get; set; }
#nullable restore
#else
        public string EntryDate { get; set; }
#endif
        /// <summary>The exitDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExitDate { get; set; }
#nullable restore
#else
        public string ExitDate { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The gender property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gender { get; set; }
#nullable restore
#else
        public string Gender { get; set; }
#endif
        /// <summary>The hometown property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hometown { get; set; }
#nullable restore
#else
        public string Hometown { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The idNr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdNr { get; set; }
#nullable restore
#else
        public string IdNr { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The loginActive property</summary>
        public bool? LoginActive { get; set; }
        /// <summary>The mobile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mobile { get; set; }
#nullable restore
#else
        public string Mobile { get; set; }
#endif
        /// <summary>The nationality property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nationality { get; set; }
#nullable restore
#else
        public string Nationality { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The postOfficeBox property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostOfficeBox { get; set; }
#nullable restore
#else
        public string PostOfficeBox { get; set; }
#endif
        /// <summary>The profil1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Profil1 { get; set; }
#nullable restore
#else
        public string Profil1 { get; set; }
#endif
        /// <summary>The profil2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Profil2 { get; set; }
#nullable restore
#else
        public string Profil2 { get; set; }
#endif
        /// <summary>The regularClasses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto>? RegularClasses { get; set; }
#nullable restore
#else
        public List<global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto> RegularClasses { get; set; }
#endif
        /// <summary>The street property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Street { get; set; }
#nullable restore
#else
        public string Street { get; set; }
#endif
        /// <summary>The userType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserType { get; set; }
#nullable restore
#else
        public string UserType { get; set; }
#endif
        /// <summary>The zip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zip { get; set; }
#nullable restore
#else
        public string Zip { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.UserInfoDto"/> and sets the default values.
        /// </summary>
        public UserInfoDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.UserInfoDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.UserInfoDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.UserInfoDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalClasses", n => { AdditionalClasses = n.GetCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto>(global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "addressLine2", n => { AddressLine2 = n.GetStringValue(); } },
                { "birthday", n => { Birthday = n.GetStringValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "emailPrivate", n => { EmailPrivate = n.GetStringValue(); } },
                { "entryDate", n => { EntryDate = n.GetStringValue(); } },
                { "exitDate", n => { ExitDate = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "gender", n => { Gender = n.GetStringValue(); } },
                { "hometown", n => { Hometown = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "idNr", n => { IdNr = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "loginActive", n => { LoginActive = n.GetBoolValue(); } },
                { "mobile", n => { Mobile = n.GetStringValue(); } },
                { "nationality", n => { Nationality = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "postOfficeBox", n => { PostOfficeBox = n.GetStringValue(); } },
                { "profil1", n => { Profil1 = n.GetStringValue(); } },
                { "profil2", n => { Profil2 = n.GetStringValue(); } },
                { "regularClasses", n => { RegularClasses = n.GetCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto>(global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "street", n => { Street = n.GetStringValue(); } },
                { "userType", n => { UserType = n.GetStringValue(); } },
                { "zip", n => { Zip = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto>("additionalClasses", AdditionalClasses);
            writer.WriteStringValue("addressLine2", AddressLine2);
            writer.WriteStringValue("birthday", Birthday);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("emailPrivate", EmailPrivate);
            writer.WriteStringValue("entryDate", EntryDate);
            writer.WriteStringValue("exitDate", ExitDate);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("gender", Gender);
            writer.WriteStringValue("hometown", Hometown);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("idNr", IdNr);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteBoolValue("loginActive", LoginActive);
            writer.WriteStringValue("mobile", Mobile);
            writer.WriteStringValue("nationality", Nationality);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("postOfficeBox", PostOfficeBox);
            writer.WriteStringValue("profil1", Profil1);
            writer.WriteStringValue("profil2", Profil2);
            writer.WriteCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.ClassInfoDto>("regularClasses", RegularClasses);
            writer.WriteStringValue("street", Street);
            writer.WriteStringValue("userType", UserType);
            writer.WriteStringValue("zip", Zip);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
