<Project>

  <PropertyGroup>
    <_VersionFile>$(MSBuildThisFileDirectory)application.properties</_VersionFile>
  </PropertyGroup>

  <Target Name="_ReadVersionFromProperties"
          BeforeTargets="GetAssemblyVersion;GenerateAssemblyInfo;_GenerateRestoreProjectSpec;Build;Pack"
          Condition="Exists('$(_VersionFile)')">
    <XmlPeek XmlInputPath="$(_VersionFile)" Query="/properties/version/text()">
      <Output TaskParameter="Result" ItemName="_VersionFromFile" />
    </XmlPeek>
    <PropertyGroup>
      <Version>@(_VersionFromFile)</Version>
    </PropertyGroup>
  </Target>

</Project>
