// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth.Mobile;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\authenticate\oauth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OauthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mobile property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth.Mobile.MobileRequestBuilder Mobile
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth.Mobile.MobileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth.OauthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/authenticate/oauth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth.OauthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OauthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/authenticate/oauth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
