// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Absencenotices;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Absencenoticestatus;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Absences;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Agenda;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Customfields;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Events;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Exams;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Filecategories;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Grades;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Homework;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Lateness;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Notifications;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Objectives;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Settings;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Topics;
using Schuly.Plugin.Schulware.Client.Api.Mobile.UserInfo;
using Schuly.Plugin.Schulware.Client.Api.Mobile.Vacations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Schuly.Plugin.Schulware.Client.Api.Mobile
{
    /// <summary>
    /// Builds and executes requests for operations under \api\mobile
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MobileRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The absencenotices property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Absencenotices.AbsencenoticesRequestBuilder Absencenotices
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Absencenotices.AbsencenoticesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The absencenoticestatus property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Absencenoticestatus.AbsencenoticestatusRequestBuilder Absencenoticestatus
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Absencenoticestatus.AbsencenoticestatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The absences property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Absences.AbsencesRequestBuilder Absences
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Absences.AbsencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The agenda property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Agenda.AgendaRequestBuilder Agenda
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Agenda.AgendaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customfields property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Customfields.CustomfieldsRequestBuilder Customfields
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Customfields.CustomfieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Events.EventsRequestBuilder Events
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exams property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Exams.ExamsRequestBuilder Exams
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Exams.ExamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filecategories property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Filecategories.FilecategoriesRequestBuilder Filecategories
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Filecategories.FilecategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The grades property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Grades.GradesRequestBuilder Grades
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Grades.GradesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The homework property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Homework.HomeworkRequestBuilder Homework
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Homework.HomeworkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lateness property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Lateness.LatenessRequestBuilder Lateness
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Lateness.LatenessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The objectives property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Objectives.ObjectivesRequestBuilder Objectives
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Objectives.ObjectivesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The studentidcard property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.StudentidcardRequestBuilder Studentidcard
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Studentidcard.StudentidcardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The topics property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Topics.TopicsRequestBuilder Topics
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Topics.TopicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userInfo property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.UserInfo.UserInfoRequestBuilder UserInfo
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.UserInfo.UserInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The vacations property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.Vacations.VacationsRequestBuilder Vacations
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.Vacations.VacationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Mobile.MobileRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MobileRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/mobile", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Mobile.MobileRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MobileRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/mobile", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
