// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Schuly.Plugin.Schulware.Client.Api.Authenticate.Mobile;
using Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth;
using Schuly.Plugin.Schulware.Client.Api.Authenticate.Unified;
using Schuly.Plugin.Schulware.Client.Api.Authenticate.Web;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Schuly.Plugin.Schulware.Client.Api.Authenticate
{
    /// <summary>
    /// Builds and executes requests for operations under \api\authenticate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthenticateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mobile property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Mobile.MobileRequestBuilder Mobile
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Mobile.MobileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unified property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Unified.UnifiedRequestBuilder Unified
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Unified.UnifiedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The web property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Web.WebRequestBuilder Web
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Web.WebRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Authenticate.AuthenticateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthenticateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/authenticate", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Authenticate.AuthenticateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthenticateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/authenticate", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
