// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Schuly.Plugin.Schulware.Client.Api.App;
using Schuly.Plugin.Schulware.Client.Api.Mobile;
using Schuly.Plugin.Schulware.Client.Api.Web;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Schuly.Plugin.Schulware.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The app property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.App.AppRequestBuilder App
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.App.AppRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mobile property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Mobile.MobileRequestBuilder Mobile
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Mobile.MobileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The web property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Web.WebRequestBuilder Web
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Web.WebRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
