// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Schuly.Plugin.Schulware.Client.Api.Web.Agenda;
using Schuly.Plugin.Schulware.Client.Api.Web.Ausweis;
using Schuly.Plugin.Schulware.Client.Api.Web.Listen;
using Schuly.Plugin.Schulware.Client.Api.Web.Noten;
using Schuly.Plugin.Schulware.Client.Api.Web.Unterricht;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Schuly.Plugin.Schulware.Client.Api.Web
{
    /// <summary>
    /// Builds and executes requests for operations under \api\web
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The agenda property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Web.Agenda.AgendaRequestBuilder Agenda
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Web.Agenda.AgendaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ausweis property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Web.Ausweis.AusweisRequestBuilder Ausweis
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Web.Ausweis.AusweisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The listen property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Web.Listen.ListenRequestBuilder Listen
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Web.Listen.ListenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The noten property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Web.Noten.NotenRequestBuilder Noten
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Web.Noten.NotenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unterricht property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Web.Unterricht.UnterrichtRequestBuilder Unterricht
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Web.Unterricht.UnterrichtRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Web.WebRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/web", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Web.WebRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/web", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
