// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Schuly.Plugin.Schulware.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Schuly.Plugin.Schulware.Client.Api.Authenticate.Login
{
    /// <summary>
    /// Builds and executes requests for operations under \api\authenticate\login
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoginRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Login.LoginRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoginRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/authenticate/login", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Login.LoginRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoginRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/authenticate/login", rawUrl)
        {
        }
        /// <summary>
        /// Unified Schulnetz auth — one endpoint for every sign-in path.Pass `session_cookies` from a previous response for a silent passwordlessre-auth, and/or `email` + `password` (+ `totp_secret`/`totp_code`) for aheadless credential login. When both are present the cookies are triedfirst and the credentials are the fallback. No browser, no WebView.Returns mobile tokens, the web session (PHPSESSID + id/transid), and therotated `session_cookies` to persist for the next call.
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto"/></returns>
        /// <param name="body">Unified Schulnetz auth — one call for every sign-in path.Pass `session_cookies` from a previous response for a silent, passwordlessre-auth, and/or `email` + `password` (+ TOTP) for a headless credentiallogin. When both are present the cookies are tried first and the credentialsare the fallback. No browser, no WebView.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Schuly.Plugin.Schulware.Client.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto?> PostAsync(global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto> PostAsync(global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Schuly.Plugin.Schulware.Client.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto>(requestInfo, global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Unified Schulnetz auth — one endpoint for every sign-in path.Pass `session_cookies` from a previous response for a silent passwordlessre-auth, and/or `email` + `password` (+ `totp_secret`/`totp_code`) for aheadless credential login. When both are present the cookies are triedfirst and the credentials are the fallback. No browser, no WebView.Returns mobile tokens, the web session (PHPSESSID + id/transid), and therotated `session_cookies` to persist for the next call.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Unified Schulnetz auth — one call for every sign-in path.Pass `session_cookies` from a previous response for a silent, passwordlessre-auth, and/or `email` + `password` (+ TOTP) for a headless credentiallogin. When both are present the cookies are tried first and the credentialsare the fallback. No browser, no WebView.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Login.LoginRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Login.LoginRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Schuly.Plugin.Schulware.Client.Api.Authenticate.Login.LoginRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LoginRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
