// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Schuly.Plugin.Schulware.Client.Api.Websession.Capture;
using Schuly.Plugin.Schulware.Client.Api.Websession.Scrape;
using Schuly.Plugin.Schulware.Client.Api.Websession.Validate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Schuly.Plugin.Schulware.Client.Api.Websession
{
    /// <summary>
    /// Builds and executes requests for operations under \api\websession
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebsessionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The capture property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Websession.Capture.CaptureRequestBuilder Capture
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Websession.Capture.CaptureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scrape property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Websession.Scrape.ScrapeRequestBuilder Scrape
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Websession.Scrape.ScrapeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validate property</summary>
        public global::Schuly.Plugin.Schulware.Client.Api.Websession.Validate.ValidateRequestBuilder Validate
        {
            get => new global::Schuly.Plugin.Schulware.Client.Api.Websession.Validate.ValidateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Websession.WebsessionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebsessionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/websession", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Api.Websession.WebsessionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebsessionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/websession", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
