// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AbsenceNoticeDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The absenceId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AbsenceId { get; set; }
#nullable restore
#else
        public string AbsenceId { get; set; }
#endif
        /// <summary>The absenceSemester property</summary>
        public int? AbsenceSemester { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The course property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Course { get; set; }
#nullable restore
#else
        public string Course { get; set; }
#endif
        /// <summary>The courseId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CourseId { get; set; }
#nullable restore
#else
        public string CourseId { get; set; }
#endif
        /// <summary>The date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Date { get; set; }
#nullable restore
#else
        public string Date { get; set; }
#endif
        /// <summary>The hourFrom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HourFrom { get; set; }
#nullable restore
#else
        public string HourFrom { get; set; }
#endif
        /// <summary>The hourTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HourTo { get; set; }
#nullable restore
#else
        public string HourTo { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The isExamLesson property</summary>
        public bool? IsExamLesson { get; set; }
        /// <summary>The profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Profile { get; set; }
#nullable restore
#else
        public string Profile { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The statusLong property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusLong { get; set; }
#nullable restore
#else
        public string StatusLong { get; set; }
#endif
        /// <summary>The studentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StudentId { get; set; }
#nullable restore
#else
        public string StudentId { get; set; }
#endif
        /// <summary>The studentIs18 property</summary>
        public bool? StudentIs18 { get; set; }
        /// <summary>The studentReason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StudentReason { get; set; }
#nullable restore
#else
        public string StudentReason { get; set; }
#endif
        /// <summary>The studentReasonTimestamp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StudentReasonTimestamp { get; set; }
#nullable restore
#else
        public string StudentReasonTimestamp { get; set; }
#endif
        /// <summary>The time property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Time { get; set; }
#nullable restore
#else
        public string Time { get; set; }
#endif
        /// <summary>The trainerAcknowledgement property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrainerAcknowledgement { get; set; }
#nullable restore
#else
        public string TrainerAcknowledgement { get; set; }
#endif
        /// <summary>The trainerComment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrainerComment { get; set; }
#nullable restore
#else
        public string TrainerComment { get; set; }
#endif
        /// <summary>The trainerCommentTimestamp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrainerCommentTimestamp { get; set; }
#nullable restore
#else
        public string TrainerCommentTimestamp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeDto"/> and sets the default values.
        /// </summary>
        public AbsenceNoticeDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absenceId", n => { AbsenceId = n.GetStringValue(); } },
                { "absenceSemester", n => { AbsenceSemester = n.GetIntValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "course", n => { Course = n.GetStringValue(); } },
                { "courseId", n => { CourseId = n.GetStringValue(); } },
                { "date", n => { Date = n.GetStringValue(); } },
                { "hourFrom", n => { HourFrom = n.GetStringValue(); } },
                { "hourTo", n => { HourTo = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isExamLesson", n => { IsExamLesson = n.GetBoolValue(); } },
                { "profile", n => { Profile = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "statusLong", n => { StatusLong = n.GetStringValue(); } },
                { "studentId", n => { StudentId = n.GetStringValue(); } },
                { "studentIs18", n => { StudentIs18 = n.GetBoolValue(); } },
                { "studentReason", n => { StudentReason = n.GetStringValue(); } },
                { "studentReasonTimestamp", n => { StudentReasonTimestamp = n.GetStringValue(); } },
                { "time", n => { Time = n.GetStringValue(); } },
                { "trainerAcknowledgement", n => { TrainerAcknowledgement = n.GetStringValue(); } },
                { "trainerComment", n => { TrainerComment = n.GetStringValue(); } },
                { "trainerCommentTimestamp", n => { TrainerCommentTimestamp = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("absenceId", AbsenceId);
            writer.WriteIntValue("absenceSemester", AbsenceSemester);
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("course", Course);
            writer.WriteStringValue("courseId", CourseId);
            writer.WriteStringValue("date", Date);
            writer.WriteStringValue("hourFrom", HourFrom);
            writer.WriteStringValue("hourTo", HourTo);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isExamLesson", IsExamLesson);
            writer.WriteStringValue("profile", Profile);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("statusLong", StatusLong);
            writer.WriteStringValue("studentId", StudentId);
            writer.WriteBoolValue("studentIs18", StudentIs18);
            writer.WriteStringValue("studentReason", StudentReason);
            writer.WriteStringValue("studentReasonTimestamp", StudentReasonTimestamp);
            writer.WriteStringValue("time", Time);
            writer.WriteStringValue("trainerAcknowledgement", TrainerAcknowledgement);
            writer.WriteStringValue("trainerComment", TrainerComment);
            writer.WriteStringValue("trainerCommentTimestamp", TrainerCommentTimestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
