// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AbsencesPageDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The absences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto>? Absences { get; set; }
#nullable restore
#else
        public List<global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto> Absences { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The lesson_reports property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto>? LessonReports { get; set; }
#nullable restore
#else
        public List<global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto> LessonReports { get; set; }
#endif
        /// <summary>The student property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Student { get; set; }
#nullable restore
#else
        public string Student { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsencesPageDto"/> and sets the default values.
        /// </summary>
        public AbsencesPageDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsencesPageDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.AbsencesPageDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.AbsencesPageDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "absences", n => { Absences = n.GetCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto>(global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lesson_reports", n => { LessonReports = n.GetCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "student", n => { Student = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto>("absences", Absences);
            writer.WriteCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto>("lesson_reports", LessonReports);
            writer.WriteStringValue("student", Student);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
