// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AbsenceNoticeStatusDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The additionalInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalInfo { get; set; }
#nullable restore
#else
        public string AdditionalInfo { get; set; }
#endif
        /// <summary>The code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The iso2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Iso2 { get; set; }
#nullable restore
#else
        public string Iso2 { get; set; }
#endif
        /// <summary>The iso3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Iso3 { get; set; }
#nullable restore
#else
        public string Iso3 { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The sort property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sort { get; set; }
#nullable restore
#else
        public string Sort { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto"/> and sets the default values.
        /// </summary>
        public AbsenceNoticeStatusDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.AbsenceNoticeStatusDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additionalInfo", n => { AdditionalInfo = n.GetStringValue(); } },
                { "code", n => { Code = n.GetStringValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "iso2", n => { Iso2 = n.GetStringValue(); } },
                { "iso3", n => { Iso3 = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "sort", n => { Sort = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("additionalInfo", AdditionalInfo);
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("iso2", Iso2);
            writer.WriteStringValue("iso3", Iso3);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("sort", Sort);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
