// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    /// <summary>
    /// Unified auth: one endpoint for every Schulnetz sign-in path.Supply a stored `context_state` for a silent, passwordless re-auth, and/or`email` + `password` (+ optional `totp_secret`) for a headless credentiallogin. When both are given, the stored cookies are tried first and thecredentials are the fallback. No browser, no WebView — `ms-entrance` walksthe Microsoft Entra flow over plain HTTP. Returns mobile tokens, the websession, and an updated `context_state` to persist.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoginRequestDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional cookie jar from a previous login, for a silent (passwordless) re-auth.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_context_state? ContextState { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_context_state ContextState { get; set; }
#endif
        /// <summary>Microsoft SSO email (for a credential login or cold-start).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Microsoft SSO password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>The Schulnetz instance base URL, e.g. https://schulnetz.example.ch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SchulnetzBaseUrl { get; set; }
#nullable restore
#else
        public string SchulnetzBaseUrl { get; set; }
#endif
        /// <summary>Base32 TOTP secret, if the account has authenticator-app MFA. Push/SMS MFA can&apos;t be done headlessly.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotpSecret { get; set; }
#nullable restore
#else
        public string TotpSecret { get; set; }
#endif
        /// <summary>UA string to use for the session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserAgent { get; set; }
#nullable restore
#else
        public string UserAgent { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto"/> and sets the default values.
        /// </summary>
        public LoginRequestDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "context_state", n => { ContextState = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_context_state>(global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_context_state.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "schulnetz_base_url", n => { SchulnetzBaseUrl = n.GetStringValue(); } },
                { "totp_secret", n => { TotpSecret = n.GetStringValue(); } },
                { "user_agent", n => { UserAgent = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_context_state>("context_state", ContextState);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("schulnetz_base_url", SchulnetzBaseUrl);
            writer.WriteStringValue("totp_secret", TotpSecret);
            writer.WriteStringValue("user_agent", UserAgent);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
