// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    /// <summary>
    /// Unified Schulnetz auth — one call for every sign-in path.Pass `session_cookies` from a previous response for a silent, passwordlessre-auth, and/or `email` + `password` (+ TOTP) for a headless credentiallogin. When both are present the cookies are tried first and the credentialsare the fallback. No browser, no WebView.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoginRequestDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Microsoft SSO email (for a credential login or cold-start).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Microsoft SSO password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>The Schulnetz instance base URL, e.g. https://schulnetz.example.ch</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SchulnetzBaseUrl { get; set; }
#nullable restore
#else
        public string SchulnetzBaseUrl { get; set; }
#endif
        /// <summary>Microsoft session cookies from a previous login, for a silent (passwordless) re-auth.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_session_cookies>? SessionCookies { get; set; }
#nullable restore
#else
        public List<global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_session_cookies> SessionCookies { get; set; }
#endif
        /// <summary>A precomputed 6-digit TOTP code, used as-is. Alternative to totp_secret.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotpCode { get; set; }
#nullable restore
#else
        public string TotpCode { get; set; }
#endif
        /// <summary>Base32 TOTP secret, if the account has authenticator-app MFA. A fresh code is generated per attempt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotpSecret { get; set; }
#nullable restore
#else
        public string TotpSecret { get; set; }
#endif
        /// <summary>UA to replay with. Microsoft binds session cookies to UA; a mismatch invalidates them.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserAgent { get; set; }
#nullable restore
#else
        public string UserAgent { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto"/> and sets the default values.
        /// </summary>
        public LoginRequestDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "schulnetz_base_url", n => { SchulnetzBaseUrl = n.GetStringValue(); } },
                { "session_cookies", n => { SessionCookies = n.GetCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_session_cookies>(global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_session_cookies.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totp_code", n => { TotpCode = n.GetStringValue(); } },
                { "totp_secret", n => { TotpSecret = n.GetStringValue(); } },
                { "user_agent", n => { UserAgent = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("schulnetz_base_url", SchulnetzBaseUrl);
            writer.WriteCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.LoginRequestDto_session_cookies>("session_cookies", SessionCookies);
            writer.WriteStringValue("totp_code", TotpCode);
            writer.WriteStringValue("totp_secret", TotpSecret);
            writer.WriteStringValue("user_agent", UserAgent);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
