// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    /// <summary>
    /// Everything a caller needs from one login: mobile tokens, the web session,and the rotated cookie jar to persist for the next (passwordless) call.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoginResponseDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>The access_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The refresh_token property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefreshToken { get; set; }
#nullable restore
#else
        public string RefreshToken { get; set; }
#endif
        /// <summary>Rotated Microsoft session cookies. The caller MUST persist these and pass them back as session_cookies on the next call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto_session_cookies>? SessionCookies { get; set; }
#nullable restore
#else
        public List<global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto_session_cookies> SessionCookies { get; set; }
#endif
        /// <summary>The session_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>The success property</summary>
        public bool? Success { get; set; }
        /// <summary>The web_session_trans_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebSessionTransId { get; set; }
#nullable restore
#else
        public string WebSessionTransId { get; set; }
#endif
        /// <summary>The web_session_user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebSessionUserId { get; set; }
#nullable restore
#else
        public string WebSessionUserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto"/> and sets the default values.
        /// </summary>
        public LoginResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_token", n => { AccessToken = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "refresh_token", n => { RefreshToken = n.GetStringValue(); } },
                { "session_cookies", n => { SessionCookies = n.GetCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto_session_cookies>(global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto_session_cookies.CreateFromDiscriminatorValue)?.AsList(); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
                { "success", n => { Success = n.GetBoolValue(); } },
                { "web_session_trans_id", n => { WebSessionTransId = n.GetStringValue(); } },
                { "web_session_user_id", n => { WebSessionUserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_token", AccessToken);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("refresh_token", RefreshToken);
            writer.WriteCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.LoginResponseDto_session_cookies>("session_cookies", SessionCookies);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteBoolValue("success", Success);
            writer.WriteStringValue("web_session_trans_id", WebSessionTransId);
            writer.WriteStringValue("web_session_user_id", WebSessionUserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
