// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScheduleEventDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The end_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDate { get; set; }
#nullable restore
#else
        public string EndDate { get; set; }
#endif
        /// <summary>The event_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventType { get; set; }
#nullable restore
#else
        public string EventType { get; set; }
#endif
        /// <summary>The fachkuerzel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fachkuerzel { get; set; }
#nullable restore
#else
        public string Fachkuerzel { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The kalenderwoche property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kalenderwoche { get; set; }
#nullable restore
#else
        public string Kalenderwoche { get; set; }
#endif
        /// <summary>The klasse property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Klasse { get; set; }
#nullable restore
#else
        public string Klasse { get; set; }
#endif
        /// <summary>The kommentar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kommentar { get; set; }
#nullable restore
#else
        public string Kommentar { get; set; }
#endif
        /// <summary>The kursid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kursid { get; set; }
#nullable restore
#else
        public string Kursid { get; set; }
#endif
        /// <summary>The kurskuerzel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kurskuerzel { get; set; }
#nullable restore
#else
        public string Kurskuerzel { get; set; }
#endif
        /// <summary>The lehrerkuerzelname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lehrerkuerzelname { get; set; }
#nullable restore
#else
        public string Lehrerkuerzelname { get; set; }
#endif
        /// <summary>The lektionswert property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lektionswert { get; set; }
#nullable restore
#else
        public string Lektionswert { get; set; }
#endif
        /// <summary>The schulanlage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Schulanlage { get; set; }
#nullable restore
#else
        public string Schulanlage { get; set; }
#endif
        /// <summary>The start_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The wochentag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Wochentag { get; set; }
#nullable restore
#else
        public string Wochentag { get; set; }
#endif
        /// <summary>The zimmer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zimmer { get; set; }
#nullable restore
#else
        public string Zimmer { get; set; }
#endif
        /// <summary>The zimmerkuerzel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zimmerkuerzel { get; set; }
#nullable restore
#else
        public string Zimmerkuerzel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.ScheduleEventDto"/> and sets the default values.
        /// </summary>
        public ScheduleEventDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.ScheduleEventDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.ScheduleEventDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.ScheduleEventDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "color", n => { Color = n.GetStringValue(); } },
                { "end_date", n => { EndDate = n.GetStringValue(); } },
                { "event_type", n => { EventType = n.GetStringValue(); } },
                { "fachkuerzel", n => { Fachkuerzel = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "kalenderwoche", n => { Kalenderwoche = n.GetStringValue(); } },
                { "klasse", n => { Klasse = n.GetStringValue(); } },
                { "kommentar", n => { Kommentar = n.GetStringValue(); } },
                { "kursid", n => { Kursid = n.GetStringValue(); } },
                { "kurskuerzel", n => { Kurskuerzel = n.GetStringValue(); } },
                { "lehrerkuerzelname", n => { Lehrerkuerzelname = n.GetStringValue(); } },
                { "lektionswert", n => { Lektionswert = n.GetStringValue(); } },
                { "schulanlage", n => { Schulanlage = n.GetStringValue(); } },
                { "start_date", n => { StartDate = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "wochentag", n => { Wochentag = n.GetStringValue(); } },
                { "zimmer", n => { Zimmer = n.GetStringValue(); } },
                { "zimmerkuerzel", n => { Zimmerkuerzel = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("end_date", EndDate);
            writer.WriteStringValue("event_type", EventType);
            writer.WriteStringValue("fachkuerzel", Fachkuerzel);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("kalenderwoche", Kalenderwoche);
            writer.WriteStringValue("klasse", Klasse);
            writer.WriteStringValue("kommentar", Kommentar);
            writer.WriteStringValue("kursid", Kursid);
            writer.WriteStringValue("kurskuerzel", Kurskuerzel);
            writer.WriteStringValue("lehrerkuerzelname", Lehrerkuerzelname);
            writer.WriteStringValue("lektionswert", Lektionswert);
            writer.WriteStringValue("schulanlage", Schulanlage);
            writer.WriteStringValue("start_date", StartDate);
            writer.WriteStringValue("text", Text);
            writer.WriteStringValue("wochentag", Wochentag);
            writer.WriteStringValue("zimmer", Zimmer);
            writer.WriteStringValue("zimmerkuerzel", Zimmerkuerzel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
