// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebAbsenceDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The acknowledged_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AcknowledgedAt { get; set; }
#nullable restore
#else
        public string AcknowledgedAt { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The additional_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalInfo { get; set; }
#nullable restore
#else
        public string AdditionalInfo { get; set; }
#endif
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The date_from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateFrom { get; set; }
#nullable restore
#else
        public string DateFrom { get; set; }
#endif
        /// <summary>The date_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateTo { get; set; }
#nullable restore
#else
        public string DateTo { get; set; }
#endif
        /// <summary>The excused property</summary>
        public bool? Excused { get; set; }
        /// <summary>The extension_deadline property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExtensionDeadline { get; set; }
#nullable restore
#else
        public string ExtensionDeadline { get; set; }
#endif
        /// <summary>The lessons property</summary>
        public int? Lessons { get; set; }
        /// <summary>The reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The reports property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto>? Reports { get; set; }
#nullable restore
#else
        public List<global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto> Reports { get; set; }
#endif
        /// <summary>The status_eae property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusEae { get; set; }
#nullable restore
#else
        public string StatusEae { get; set; }
#endif
        /// <summary>The trainer_comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrainerComment { get; set; }
#nullable restore
#else
        public string TrainerComment { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto"/> and sets the default values.
        /// </summary>
        public WebAbsenceDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.WebAbsenceDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acknowledged_at", n => { AcknowledgedAt = n.GetStringValue(); } },
                { "additional_info", n => { AdditionalInfo = n.GetStringValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "date_from", n => { DateFrom = n.GetStringValue(); } },
                { "date_to", n => { DateTo = n.GetStringValue(); } },
                { "excused", n => { Excused = n.GetBoolValue(); } },
                { "extension_deadline", n => { ExtensionDeadline = n.GetStringValue(); } },
                { "lessons", n => { Lessons = n.GetIntValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "reports", n => { Reports = n.GetCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto>(global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status_eae", n => { StatusEae = n.GetStringValue(); } },
                { "trainer_comment", n => { TrainerComment = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("acknowledged_at", AcknowledgedAt);
            writer.WriteStringValue("additional_info", AdditionalInfo);
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("date_from", DateFrom);
            writer.WriteStringValue("date_to", DateTo);
            writer.WriteBoolValue("excused", Excused);
            writer.WriteStringValue("extension_deadline", ExtensionDeadline);
            writer.WriteIntValue("lessons", Lessons);
            writer.WriteStringValue("reason", Reason);
            writer.WriteCollectionOfObjectValues<global::Schuly.Plugin.Schulware.Client.Models.AbsenceReportDto>("reports", Reports);
            writer.WriteStringValue("status_eae", StatusEae);
            writer.WriteStringValue("trainer_comment", TrainerComment);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
