// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Schuly.Plugin.Schulware.Client.Models
{
    /// <summary>
    /// Response DTO for web session capture.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebSessionResponseDto : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>All captured session cookies</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_cookies? Cookies { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_cookies Cookies { get; set; }
#endif
        /// <summary>Status message</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>PHPSESSID value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>Session parameters (id, transid, navigation_urls)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_session_info? SessionInfo { get; set; }
#nullable restore
#else
        public global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_session_info SessionInfo { get; set; }
#endif
        /// <summary>Whether session capture was successful</summary>
        public bool? Success { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto"/> and sets the default values.
        /// </summary>
        public WebSessionResponseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cookies", n => { Cookies = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_cookies>(global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_cookies.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
                { "session_info", n => { SessionInfo = n.GetObjectValue<global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_session_info>(global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_session_info.CreateFromDiscriminatorValue); } },
                { "success", n => { Success = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_cookies>("cookies", Cookies);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteObjectValue<global::Schuly.Plugin.Schulware.Client.Models.WebSessionResponseDto_session_info>("session_info", SessionInfo);
            writer.WriteBoolValue("success", Success);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
